module com.destrostudios.icetea.core {
    requires transitive org.lwjgl;
    requires transitive org.lwjgl.assimp;
    requires transitive org.lwjgl.assimp.natives;
    requires transitive org.lwjgl.glfw;
    requires transitive org.lwjgl.glfw.natives;
    requires transitive org.lwjgl.openal;
    requires transitive org.lwjgl.openal.natives;
    requires transitive org.lwjgl.shaderc;
    requires transitive org.lwjgl.shaderc.natives;
    requires transitive org.lwjgl.stb;
    requires transitive org.lwjgl.stb.natives;
    requires transitive org.lwjgl.vulkan;
    requires transitive org.joml;
    requires obj;
    requires jgltf.model;
    requires static lombok;

    exports com.destrostudios.icetea.core;
    exports com.destrostudios.icetea.core.animation;
    exports com.destrostudios.icetea.core.asset;
    exports com.destrostudios.icetea.core.asset.loader;
    exports com.destrostudios.icetea.core.asset.locator;
    exports com.destrostudios.icetea.core.camera;
    exports com.destrostudios.icetea.core.camera.systems;
    exports com.destrostudios.icetea.core.collision;
    exports com.destrostudios.icetea.core.compute;
    exports com.destrostudios.icetea.core.data;
    exports com.destrostudios.icetea.core.data.values;
    exports com.destrostudios.icetea.core.filter;
    exports com.destrostudios.icetea.core.font;
    exports com.destrostudios.icetea.core.input;
    exports com.destrostudios.icetea.core.material;
    exports com.destrostudios.icetea.core.material.descriptor;
    exports com.destrostudios.icetea.core.mesh;
    exports com.destrostudios.icetea.core.model;
    exports com.destrostudios.icetea.core.render;
    exports com.destrostudios.icetea.core.render.bucket;
    exports com.destrostudios.icetea.core.render.bucket.comparators;
    exports com.destrostudios.icetea.core.render.filter;
    exports com.destrostudios.icetea.core.render.fullscreen;
    exports com.destrostudios.icetea.core.render.scene;
    exports com.destrostudios.icetea.core.render.shadow;
    exports com.destrostudios.icetea.core.scene;
    exports com.destrostudios.icetea.core.scene.gui;
    exports com.destrostudios.icetea.core.shader;
    exports com.destrostudios.icetea.core.system;
    exports com.destrostudios.icetea.core.texture;
    exports com.destrostudios.icetea.core.util;
}
